//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int PositionID { get; set; }
        public int ShopID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsActive { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
